/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dwuma
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JInternalFrame();
        cbxGender = new javax.swing.JComboBox<>();
        lblLogin = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        tfldUsername = new javax.swing.JTextField();
        tfldPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        Help = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        Admin = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login.setVisible(false);
        Login.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        Login.getContentPane().add(cbxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        lblLogin.setFont(new java.awt.Font("Microsoft YaHei", 1, 48)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login");
        Login.getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        lblGender.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender");
        Login.getContentPane().add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        lblUsername.setFont(new java.awt.Font("Microsoft YaHei", 3, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        Login.getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 130, -1));

        tfldUsername.setText("Enter your name");
        tfldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfldUsernameActionPerformed(evt);
            }
        });
        Login.getContentPane().add(tfldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 140, -1));

        tfldPassword.setText("Enter your password");
        Login.getContentPane().add(tfldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 150, -1));

        lblPassword.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        Login.getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        Help.setText("Help");
        Login.getContentPane().add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        btnLogin.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        Login.getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\dwuma\\Desktop\\Login.jpg")); // NOI18N
        Login.getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 480));

        Admin.setVisible(true);
        Admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
            .addComponent(Admin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Admin;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Help;
    private javax.swing.JInternalFrame Login;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbxGender;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField tfldPassword;
    private javax.swing.JTextField tfldUsername;
    // End of variables declaration//GEN-END:variables
}
